import type { CategoryItem } from "./types";
import {
  FaMobileAlt,
  FaTabletAlt,
  FaLaptop,
  FaTv,
  FaCamera,
  FaGamepad,
  FaPlug,
  FaTshirt,
  FaMale,
  FaFemale,
  FaChild,
  FaShoePrints,
  FaSuitcase,
  FaHome,
  FaCouch,
  FaUtensils,
  FaBath,
  FaPaintRoller,
  FaTree,
  FaBook,
  FaBookOpen,
  FaGraduationCap,
  FaFileAlt,
  FaBookReader,
  FaMusic,
  FaFootballBall,
  FaDumbbell,
  FaMountain,
  FaCampground,
  FaBicycle,
  FaCar,
  FaWrench,
  FaCarSide,
  FaTruckPickup,
  FaHammer,
  FaBroom,
  FaLock,
  FaBriefcase,
  FaBalanceScale,
  FaBullhorn,
  FaShippingFast,
  FaHeartbeat,
  FaStethoscope,
  FaCalendarAlt,
  FaGlassCheers,
  FaPlane,
  FaPalette,
  FaIndustry,
  FaPrint,
  FaCogs,
  FaTruck,
} from "react-icons/fa";

export const mockCategories: CategoryItem[] = [
  // ========== ECOMMERCE & SWAPPING CATEGORIES ==========
  {
    name: "Electronics",
    icon: FaMobileAlt,
    platforms: ["ecommerce"],
    childItems: [
      { name: "Phones & Tablets", icon: FaTabletAlt, platforms: ["ecommerce"] },
      { name: "Laptops & Computers", icon: FaLaptop, platforms: ["ecommerce"] },
      { name: "TV & Audio", icon: FaTv, platforms: ["ecommerce"] },
      { name: "Cameras & Photo", icon: FaCamera, platforms: ["ecommerce"] },
      { name: "Gaming Consoles", icon: FaGamepad, platforms: ["ecommerce"] },
      { name: "Accessories", icon: FaPlug, platforms: ["ecommerce"] },
    ],
  },
  {
    name: "Fashion & Clothing",
    icon: FaTshirt,
    platforms: ["ecommerce", "swapping"],
    childItems: [
      { name: "Men's Clothing", icon: FaMale, platforms: ["ecommerce", "swapping"] },
      { name: "Women's Clothing", icon: FaFemale, platforms: ["ecommerce", "swapping"] },
      { name: "Kids' Clothing", icon: FaChild, platforms: ["ecommerce", "swapping"] },
      { name: "Shoes", icon: FaShoePrints, platforms: ["ecommerce", "swapping"] },
      { name: "Bags & Accessories", icon: FaSuitcase, platforms: ["ecommerce", "swapping"] },
    ],
  },
  {
    name: "Home & Garden",
    icon: FaHome,
    platforms: ["ecommerce", "swapping"],
    childItems: [
      { name: "Furniture", icon: FaCouch, platforms: ["ecommerce", "swapping"] },
      { name: "Kitchen & Dining", icon: FaUtensils, platforms: ["ecommerce", "swapping"] },
      { name: "Bedding & Bath", icon: FaBath, platforms: ["ecommerce", "swapping"] },
      { name: "Home Decor", icon: FaPaintRoller, platforms: ["ecommerce", "swapping"] },
      { name: "Garden & Outdoor", icon: FaTree, platforms: ["ecommerce", "swapping"] },
    ],
  },
  {
    name: "Books & Media",
    icon: FaBook,
    platforms: ["ecommerce", "swapping"],
    childItems: [
      { name: "Fiction", icon: FaBookOpen, platforms: ["ecommerce", "swapping"] },
      { name: "Non-Fiction", icon: FaFileAlt, platforms: ["ecommerce", "swapping"] },
      { name: "Textbooks", icon: FaGraduationCap, platforms: ["ecommerce", "swapping"] },
      { name: "Comics & Manga", icon: FaBookReader, platforms: ["ecommerce", "swapping"] },
      { name: "Movies & Music", icon: FaMusic, platforms: ["ecommerce", "swapping"] },
    ],
  },
  {
    name: "Sports & Outdoors",
    icon: FaFootballBall,
    platforms: ["ecommerce", "swapping"],
    childItems: [
      { name: "Sports Equipment", icon: FaFootballBall, platforms: ["ecommerce", "swapping"] },
      { name: "Exercise & Fitness", icon: FaDumbbell, platforms: ["ecommerce", "swapping"] },
      { name: "Outdoor Gear", icon: FaMountain, platforms: ["ecommerce", "swapping"] },
      { name: "Camping & Hiking", icon: FaCampground, platforms: ["ecommerce", "swapping"] },
      { name: "Cycling", icon: FaBicycle, platforms: ["ecommerce", "swapping"] },
    ],
  },

  // ========== BOOKING CATEGORIES (Real Georgian Services) ==========
  {
    name: "Automotive Services",
    icon: FaCar,
    platforms: ["booking"],
    childItems: [
      { name: "Auto-Moto Service", icon: FaWrench, platforms: ["booking"] },
      { name: "Car Rental", icon: FaCarSide, platforms: ["booking"] },
      { name: "Tow Truck Service", icon: FaTruckPickup, platforms: ["booking"] },
    ],
  },
  {
    name: "Home & Property",
    icon: FaHome,
    platforms: ["booking"],
    childItems: [
      { name: "Furniture & Interior", icon: FaCouch, platforms: ["booking"] },
      { name: "Construction & Repair", icon: FaHammer, platforms: ["booking"] },
      { name: "Cleaning & Organization", icon: FaBroom, platforms: ["booking"] },
      { name: "Locks & Safes", icon: FaLock, platforms: ["booking"] },
    ],
  },
  {
    name: "Professional Services",
    icon: FaBriefcase,
    platforms: ["booking"],
    childItems: [
      { name: "Legal & Financial Services", icon: FaBalanceScale, platforms: ["booking"] },
      { name: "Computer Services", icon: FaLaptop, platforms: ["booking"] },
      { name: "Advertising Services", icon: FaBullhorn, platforms: ["booking"] },
      { name: "Courier Service", icon: FaShippingFast, platforms: ["booking"] },
    ],
  },
  {
    name: "Personal Care & Wellness",
    icon: FaHeartbeat,
    platforms: ["booking"],
    childItems: [
      { name: "Beauty Fitness Sports", icon: FaDumbbell, platforms: ["booking"] },
      { name: "Medicine Healthcare", icon: FaStethoscope, platforms: ["booking"] },
    ],
  },
  {
    name: "Events & Entertainment",
    icon: FaCalendarAlt,
    platforms: ["booking"],
    childItems: [
      { name: "Event Services", icon: FaGlassCheers, platforms: ["booking"] },
      { name: "Entertainment", icon: FaMusic, platforms: ["booking"] },
      { name: "Travel Tourism", icon: FaPlane, platforms: ["booking"] },
    ],
  },
  {
    name: "Education & Learning",
    icon: FaGraduationCap,
    platforms: ["booking"],
    childItems: [
      { name: "Education", icon: FaBook, platforms: ["booking"] },
      { name: "Art", icon: FaPalette, platforms: ["booking"] },
    ],
  },
  {
    name: "Business & Equipment",
    icon: FaIndustry,
    platforms: ["booking"],
    childItems: [
      { name: "Business Equipment", icon: FaPrint, platforms: ["booking"] },
      { name: "Special Equipment Service", icon: FaCogs, platforms: ["booking"] },
      { name: "Transportation Service", icon: FaTruck, platforms: ["booking"] },
    ],
  },
];
